package: cloud.lazycat.webshell.lcmd
version: 0.7.0
name: LCMD WebShell
description: LCMD WebShell for LightOS
min_os_version: v1.5.2
permissions:
  required:
    - lightos.manage
locales:
  zh:
    name: LCMD WebShell
    description: LCMD WebShell for LightOS
